 steps:
  # Building front end
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 'packages/client/', '--platform', 'linux/amd64', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'frontend', '--image', 'us-docker.pkg.dev/nachostocks/frontend', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
